<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../style/style.css">
    <title>Utilisateurs</title>
</head>
<body>
    <h1>Liste des utilisateurs :</h1>

    <div>
        <a href = "/users/create">Créer</a>
    </div>

    <table>
        <thead>
            <th>ID</th>
            <th>Nom</th>
            <th>Âge</th>
            <th>Détails</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </thead>

        <tbody>
            <% allUsers.forEach( (u) => { %>
            <tr>
                <td><%= u.id %></td>
                <td><%= u.name %></td>
                <td> <%= u.age %></td>
                <td><a href  = "/users/<%= u.id %>">Détails</a></td>
                <td><a href = "/users/update/<%= u.id %>">Modifier</a></td>
                <td><button onclick="deleteUser('<%= u.id %>')">Supprimer</td>
            </tr>
            <% }); %>
        </tbody>
    </table>
</body>
</html>

<script>
    async function deleteUser(userId) {
        const confirmed = confirm("Are you sure you want to delete this user?");

        if (confirmed) {
            try {
                fetch(`/users/delete/${userId}`, {
                    method: 'DELETE',
                })
                // problème : ni then ni catch atteint après la réalisation du fetch
                .then(async () => {
                    alert("User deleted successfully");
                    location.reload();
                })
                .catch(() => {
                    alert("Failed to delete user")
                });
            } catch (error) {
                alert("An error occurred: " + error.message);
            }
        }
    }
</script>